### ISSUE TITLE
run mmdet2trt() failed

### ISSUE THREAD

**Issue by whunamikey** [grimoire/mmdetection-to-tensorrt#10]
Hi,
I used the latest version of mmdetection-to-tensorrt,and the latest version of amirstan_plugin, I run mmdet2trt failed.
my model configuration is as follows:
`    CFG='./configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
    CHECK_POINT='./checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'`

and then I called mmdet2trt api as follows:
`    trt_model, torch_model = mmdet2trt(ConfigInfo.CFG, ConfigInfo.CHECK_POINT, opt_shape_param=None, fp16_mode=False,
                                       max_workspace_size=1 << 30, return_warp_model=True)`

but I got this failed issue:

`root@de6cc444df48:/home/install-file/tensorrt/mmdetection-to-tensorrt-master# python test_mmdet2trt.py  
Warning: Encountered known unsupported method torch.Tensor.new_zeros 
Warning: Encountered known unsupported method torch.Tensor.new_tensor 
Warning: Encountered known unsupported method torch.Tensor.new_tensor 
python: /home/install-file/tensorrt/amirstan_plugin/src/plugin/repeatDimsPlugin/repeatDimsPlugin.cpp:144: virtual  nvinfer1::DataType amirstan::plugin::RepeatDimsPluginDynamic::getOutputDataType(int, const nvinfer1::DataType*, int) const: Assertion `nbInputs == 1' failed. 
Aborted (core dumped) 
`
thanks

**Comment by cefengxu** [comment]
。。。 may be the [amirstan_plugin]( https://github.com/grimoire/amirstan_plugin) should be re clone and rebuilded again?

**Comment by whunamikey** [comment]
my amirstan_plugin is not the latest version, I update it to the latest one, the problem can be saved.
