### ISSUE TITLE
mmdetection 的cascade_dcn_fpn50 转化为tensorrt后，采用本项目，发现转化成deepstream的模型比转化成tensorrt的模型精度较低，有些类阈值很低，有啥排查方法么

### ISSUE THREAD

**Issue by pangchao-git** [grimoire/mmdetection-to-tensorrt#110]
**Describe the bug**

**To Reproduce**
Code snippet about how to reproduce the bug.

**environment:**
Please provide your environment by:

```python
python tools/collect_env.py
```

Please paste the result here.

**Additional context**

**Comment by grimoire** [comment]
转换成deepstream是指什么？deepstream应该是直接使用TensorRT的模型的吧。
deepstream的预处理方式可能和mmdet中定义的有些不同，可以针对这一点做一些检查

**Comment by pangchao-git** [comment]
模型是rgb训练的,修改deepstream的配置文件设置输入是rgb,问题解决了
