### ISSUE TITLE
Thx to your great works. I have some problems on installing Amirstan_plugin. So can you help me?

### ISSUE THREAD

**Issue by jwyng2000** [grimoire/mmdetection-to-tensorrt#121]
Hello. 
My Development enviroment
-cuda version is 11.1 / torch version is 1.10.1 / Ubuntu 20.04 / python 3.8 / TensorRT 8.0 GA Tar version

I want to change my checkpoints yolact and mask_rcnn in MMDET to tensorrt.
so i read the manuel you write. I followed Installing step to TensorRT Install. 
And then i got error message when i type this querry in my pycharm.
`make -j10`

the error message is this
`In file included from /usr/local/cuda/include/channel_descriptor.h:61,
                 from /usr/local/cuda/include/cuda_runtime.h:95,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/batchedNMSPlugin/plugin.h:18,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/batchedNMSPlugin/bboxUtils.h:19,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/batchedNMSPlugin/batchedNMSInference.cpp:16:
/usr/local/cuda/include/cuda_runtime_api.h:13017:45: error: expected initializer before ‘cudaGetFuncBySymbol’
13017 | extern __host__ cudaError_t CUDARTAPI_CDECL cudaGetFuncBySymbol(cudaFunction_t* functionPtr, const void* symbolPtr);
      |                                             ^~~~~~~~~~~~~~~~~~~
In file included from /usr/local/cuda/include/channel_descriptor.h:61,
                 from /usr/local/cuda/include/cuda_runtime.h:95,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/deformableConvPlugin/deform_conv_cuda.cpp:5:
/usr/local/cuda/include/cuda_runtime_api.h:13017:45: error: expected initializer before ‘cudaGetFuncBySymbol’
13017 | extern __host__ cudaError_t CUDARTAPI_CDECL cudaGetFuncBySymbol(cudaFunction_t* functionPtr, const void* symbolPtr);
      |                                             ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h:19,
                 from /usr/include/x86_64-linux-gnu/NvInferLegacyDims.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferImpl.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferRuntime.h:22,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/gridAnchorDynamicPlugin/../common/layer_base.h:4,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/gridAnchorDynamicPlugin/gridAnchorDynamicPlugin.h:9,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/gridAnchorDynamicPlugin/gridAnchorDynamicPlugin.cpp:2:
/usr/local/cuda/include/cuda_runtime_api.h:13017:45: error: expected initializer before ‘cudaGetFuncBySymbol’
13017 | extern __host__ cudaError_t CUDARTAPI_CDECL cudaGetFuncBySymbol(cudaFunction_t* functionPtr, const void* symbolPtr);
      |                                             ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h:19,
                 from /usr/include/x86_64-linux-gnu/NvInferLegacyDims.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferImpl.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferRuntime.h:22,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/carafeFeatureReassemblePlugin/../common/layer_base.h:4,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/carafeFeatureReassemblePlugin/carafeFeatureReassemblePlugin.h:9,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/carafeFeatureReassemblePlugin/carafeFeatureReassemblePlugin.cpp:2:
/usr/local/cuda/include/cuda_runtime_api.h:13017:45: error: expected initializer before ‘cudaGetFuncBySymbol’
13017 | extern __host__ cudaError_t CUDARTAPI_CDECL cudaGetFuncBySymbol(cudaFunction_t* functionPtr, const void* symbolPtr);
      |                                             ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h:19,
                 from /usr/include/x86_64-linux-gnu/NvInferLegacyDims.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferImpl.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferRuntime.h:22,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/gridSamplePlugin/../common/layer_base.h:4,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/gridSamplePlugin/gridSamplePlugin.h:9,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/gridSamplePlugin/gridSamplePlugin.cpp:2:
/usr/local/cuda/include/cuda_runtime_api.h:13017:45: error: expected initializer before ‘cudaGetFuncBySymbol’
13017 | extern __host__ cudaError_t CUDARTAPI_CDECL cudaGetFuncBySymbol(cudaFunction_t* functionPtr, const void* symbolPtr);
      |                                             ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h:19,
                 from /usr/include/x86_64-linux-gnu/NvInferLegacyDims.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferImpl.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferRuntime.h:22,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/groupNormPlugin/../common/layer_base.h:4,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/groupNormPlugin/groupNormPlugin.h:9,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/groupNormPlugin/groupNormPlugin.cpp:2:
/usr/local/cuda/include/cuda_runtime_api.h:13017:45: error: expected initializer before ‘cudaGetFuncBySymbol’
13017 | extern __host__ cudaError_t CUDARTAPI_CDECL cudaGetFuncBySymbol(cudaFunction_t* functionPtr, const void* symbolPtr);
      |                                             ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h:19,
                 from /usr/include/x86_64-linux-gnu/NvInferLegacyDims.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferImpl.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferRuntime.h:22,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/deformablePoolPlugin/../common/layer_base.h:4,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/deformablePoolPlugin/deformablePoolPlugin.h:9,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/deformablePoolPlugin/deformablePoolPlugin.cpp:2:
/usr/local/cuda/include/cuda_runtime_api.h:13017:45: error: expected initializer before ‘cudaGetFuncBySymbol’
13017 | extern __host__ cudaError_t CUDARTAPI_CDECL cudaGetFuncBySymbol(cudaFunction_t* functionPtr, const void* symbolPtr);
      |                                             ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h:19,
                 from /usr/include/x86_64-linux-gnu/NvInferLegacyDims.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferImpl.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferRuntime.h:22,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/roiExtractorPlugin/../common/layer_base.h:4,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/roiExtractorPlugin/roiExtractorPlugin.h:9,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/roiExtractorPlugin/roiExtractorPlugin.cpp:2:
/usr/local/cuda/include/cuda_runtime_api.h:13017:45: error: expected initializer before ‘cudaGetFuncBySymbol’
13017 | extern __host__ cudaError_t CUDARTAPI_CDECL cudaGetFuncBySymbol(cudaFunction_t* functionPtr, const void* symbolPtr);
      |                                             ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h:19,
                 from /usr/include/x86_64-linux-gnu/NvInferLegacyDims.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferImpl.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferRuntime.h:22,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/adaptivePoolPlugin/../common/layer_base.h:4,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/adaptivePoolPlugin/adaptivePoolPlugin.h:9,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/adaptivePoolPlugin/adaptivePoolPlugin.cpp:2:
/usr/local/cuda/include/cuda_runtime_api.h:13017:45: error: expected initializer before ‘cudaGetFuncBySymbol’
13017 | extern __host__ cudaError_t CUDARTAPI_CDECL cudaGetFuncBySymbol(cudaFunction_t* functionPtr, const void* symbolPtr);
      |                                             ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h:19,
                 from /usr/include/x86_64-linux-gnu/NvInferLegacyDims.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferImpl.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferRuntime.h:22,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/delta2bboxPlugin/../common/layer_base.h:4,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/delta2bboxPlugin/delta2bboxPlugin.h:9,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/delta2bboxPlugin/delta2bboxPlugin.cpp:2:
/usr/local/cuda/include/cuda_runtime_api.h:13017:45: error: expected initializer before ‘cudaGetFuncBySymbol’
13017 | extern __host__ cudaError_t CUDARTAPI_CDECL cudaGetFuncBySymbol(cudaFunction_t* functionPtr, const void* symbolPtr);
      |                                             ^~~~~~~~~~~~~~~~~~~
make[2]: *** [src/plugin/batchedNMSPlugin/CMakeFiles/batchedNMSPlugin_static.dir/build.make:2395: src/plugin/batchedNMSPlugin/CMakeFiles/batchedNMSPlugin_static.dir/batchedNMSInference.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:551: src/plugin/batchedNMSPlugin/CMakeFiles/batchedNMSPlugin_static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 21%] Building CXX object src/plugin/deformableConvPlugin/CMakeFiles/deformableConvPlugin_static.dir/deformableConvPlugin.cpp.o
make[2]: *** [src/plugin/deformableConvPlugin/CMakeFiles/deformableConvPlugin_static.dir/build.make:274: src/plugin/deformableConvPlugin/CMakeFiles/deformableConvPlugin_static.dir/deform_conv_cuda.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/plugin/gridAnchorDynamicPlugin/CMakeFiles/gridAnchorDynamicPlugin_static.dir/build.make:276: src/plugin/gridAnchorDynamicPlugin/CMakeFiles/gridAnchorDynamicPlugin_static.dir/gridAnchorDynamicPlugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:681: src/plugin/gridAnchorDynamicPlugin/CMakeFiles/gridAnchorDynamicPlugin_static.dir/all] Error 2
make[2]: *** [src/plugin/carafeFeatureReassemblePlugin/CMakeFiles/carafeFeatureReassemblePlugin_static.dir/build.make:273: src/plugin/carafeFeatureReassemblePlugin/CMakeFiles/carafeFeatureReassemblePlugin_static.dir/carafeFeatureReassemblePlugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:577: src/plugin/carafeFeatureReassemblePlugin/CMakeFiles/carafeFeatureReassemblePlugin_static.dir/all] Error 2
make[2]: *** [src/plugin/gridSamplePlugin/CMakeFiles/gridSamplePlugin_static.dir/build.make:276: src/plugin/gridSamplePlugin/CMakeFiles/gridSamplePlugin_static.dir/gridSamplePlugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:707: src/plugin/gridSamplePlugin/CMakeFiles/gridSamplePlugin_static.dir/all] Error 2
make[2]: *** [src/plugin/groupNormPlugin/CMakeFiles/groupNormPlugin_static.dir/build.make:277: src/plugin/groupNormPlugin/CMakeFiles/groupNormPlugin_static.dir/groupNormPlugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:733: src/plugin/groupNormPlugin/CMakeFiles/groupNormPlugin_static.dir/all] Error 2
make[2]: *** [src/plugin/deformablePoolPlugin/CMakeFiles/deformablePoolPlugin_static.dir/build.make:276: src/plugin/deformablePoolPlugin/CMakeFiles/deformablePoolPlugin_static.dir/deformablePoolPlugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:629: src/plugin/deformablePoolPlugin/CMakeFiles/deformablePoolPlugin_static.dir/all] Error 2
make[2]: *** [src/plugin/adaptivePoolPlugin/CMakeFiles/adaptivePoolPlugin_static.dir/build.make:276: src/plugin/adaptivePoolPlugin/CMakeFiles/adaptivePoolPlugin_static.dir/adaptivePoolPlugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:525: src/plugin/adaptivePoolPlugin/CMakeFiles/adaptivePoolPlugin_static.dir/all] Error 2
make[2]: *** [src/plugin/roiExtractorPlugin/CMakeFiles/roiExtractorPlugin_static.dir/build.make:274: src/plugin/roiExtractorPlugin/CMakeFiles/roiExtractorPlugin_static.dir/roiExtractorPlugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:759: src/plugin/roiExtractorPlugin/CMakeFiles/roiExtractorPlugin_static.dir/all] Error 2
make[2]: *** [src/plugin/delta2bboxPlugin/CMakeFiles/delta2bboxPlugin_static.dir/build.make:896: src/plugin/delta2bboxPlugin/CMakeFiles/delta2bboxPlugin_static.dir/delta2bboxPlugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:655: src/plugin/delta2bboxPlugin/CMakeFiles/delta2bboxPlugin_static.dir/all] Error 2
In file included from /usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h:19,
                 from /usr/include/x86_64-linux-gnu/NvInferLegacyDims.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferImpl.h:16,
                 from /usr/include/x86_64-linux-gnu/NvInferRuntime.h:22,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/deformableConvPlugin/../common/layer_base.h:4,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/deformableConvPlugin/deformableConvPlugin.h:9,
                 from /home/jwyng2000/PycharmProjects/pythonProject/newtst/mmdetection/amirstan_plugin/src/plugin/deformableConvPlugin/deformableConvPlugin.cpp:2:
/usr/local/cuda/include/cuda_runtime_api.h:13017:45: error: expected initializer before ‘cudaGetFuncBySymbol’
13017 | extern __host__ cudaError_t CUDARTAPI_CDECL cudaGetFuncBySymbol(cudaFunction_t* functionPtr, const void* symbolPtr);
      |                                             ^~~~~~~~~~~~~~~~~~~
make[2]: *** [src/plugin/deformableConvPlugin/CMakeFiles/deformableConvPlugin_static.dir/build.make:288: src/plugin/deformableConvPlugin/CMakeFiles/deformableConvPlugin_static.dir/deformableConvPlugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:603: src/plugin/deformableConvPlugin/CMakeFiles/deformableConvPlugin_static.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
`

How can i fix it? I will very appreciate if you answer this issue.

Thx for your works again.

**Comment by grimoire** [comment]
Looks like the compiler is not able to compile cuda code. Please make sure you have cuda installed.

**Comment by jwyng2000** [comment]
> Thankyou for your reply !! thank you. i rewrite on amirtstan github issues so i link it on this reply.
I think cmake detected cuda11.1 but not sure. here is the link.

https://github.com/grimoire/amirstan_plugin/issues/34

**Comment by jwyng2000** [comment]
I found solution. I changed cmakelist.txt at Amirsta_plugin folder. I changed 
`# cuda
FIND_PACKAGE(CUDA REQUIRED)
if(NOT CMAKE_CUDA_DEVICE_LINK_LIBRARY)
  set(CMAKE_CUDA_DEVICE_LINK_LIBRARY
    "<CMAKE_CUDA_COMPILER> ${CMAKE_CUDA_HOST_FLAGS} <LANGUAGE_COMPILE_FLAGS> ${CMAKE_CUDA_COMPILE_OPTIONS_PIC} ${_CMAKE_CUDA_EXTRA_DEVICE_LINK_FLAGS} -shared -dlink <OBJECTS> -o <TARGET> <LINK_LIBRARIES>${__IMPLICT_DLINK_FLAGS}")
endif()
if(NOT CMAKE_CUDA_DEVICE_LINK_EXECUTABLE)
  set(CMAKE_CUDA_DEVICE_LINK_EXECUTABLE
    "<CMAKE_CUDA_COMPILER> ${CMAKE_CUDA_HOST_FLAGS} <FLAGS> ${CMAKE_CUDA_COMPILE_OPTIONS_PIC} ${_CMAKE_CUDA_EXTRA_DEVICE_LINK_FLAGS} -shared -dlink <OBJECTS> -o <TARGET> <LINK_LIBRARIES>${__IMPLICT_DLINK_FLAGS}")
endif()
**INCLUDE_DIRECTORIES(/usr/local/cuda-11.1/targets/x86_64-linux/include)**`

I fixed INCLUDE_DIRECTORIES to my real Cuda path like (/usr/local/cuda-11.1/targets/x86_64-linux/include)
