### ISSUE TITLE
plugin not found. when import mmdet2trt

### ISSUE THREAD

**Issue by cefengxu** [grimoire/mmdetection-to-tensorrt#2]
Requirement has been build success:
- mmdet == 2.3.0
- https://github.com/grimoire/torch2trt_dynamic
- https://github.com/grimoire/amirstan_plugin     --> libamirstan_plugin.so based on gcc7.1

to run the code below:
`import mmdet2trt`

however , output the log as follow:
`plugin not found.`

**Comment by grimoire** [comment]
hi
Did you add the `export AMIRSTAN_LIBRARY_PATH=<amirstan_plugin_root>/build/lib` to your envoirment?

**Comment by cefengxu** [comment]
> hi
> Did you add the `export AMIRSTAN_LIBRARY_PATH=<amirstan_plugin_root>/build/lib` to your envoirment?

Thanks.
Updating ~/.bashrc with AMIRSTAN_LIBRARY_PATH and then the issue be resolved. :+1:
