### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by cefengxu** [grimoire/mmdetection-to-tensorrt#3]
- finishing all build about _https://github.com/grimoire/mmdetection-to-tensorrt_ ;
- verifiyng _https://github.com/grimoire/torch2trt_dynamic_  , normal operation ;

when using code on pyCharm as follow:

```
import torch
import mmdet2trt

cfg_path = 'faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
weight_path = 'faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'
save_path = 'helloworld.trt'
opt_shape_param=[
    [   [1,3,320,320],      # min shape
        [1,3,800,1344],     # optimize shape
        [1,3,1344,1344],    # max shape ] ]
max_workspace_size=1<<30    # some module need large workspace, add workspace size when OOM.
trt_model = mmdet2trt(cfg_path, weight_path, opt_shape_param=opt_shape_param, fp16_mode=True, max_workspace_size=max_workspace_size)
```
however, error log output and Python be quit force.
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

debuging from 'import mmdet2trt' via Python Console and found the code break from 
`
import matplotlib.pyplot as plt 
`in  ./mmdetection/mmdet/apis/inference.py

Curiously, when i run the demo from mmdetection (mmdetecion/demo/image_demo.py) and it runs normally. At least it should be comfirmed  mmdetecion is normally. 

So, what's problem about this case ?

**Comment by grimoire** [comment]
Hi
I googled this error :
https://github.com/matplotlib/matplotlib/issues/9294
https://www.xspdf.com/help/51312698.html

most of them are caused by QT/matplotlib conflict.

Can you run the code in console(without pycharm or any ide), see if it works.

If the error still exist. please provide detail error log and your enviroment( os, pytorch version, cuda version etc). I will try.

**Comment by cefengxu** [comment]
> Hi
> I googled this error :
> [matplotlib/matplotlib#9294](https://github.com/matplotlib/matplotlib/issues/9294)
> https://www.xspdf.com/help/51312698.html
> 
> most of them are caused by QT/matplotlib conflict.
> 
> Can you run the code in console(without pycharm or any ide), see if it works.
> 
> If the error still exist. please provide detail error log and your enviroment( os, pytorch version, cuda version etc). I will try.

yes , i run the code in Console and Terminal , but still get the same error.
**detail error**：
not detail error but just the ' Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)  ' 

**deve envirooment**：
-os                   : ubuntu 16.04
- python           : 3.7.6
- pytorch          : 1.6.0a0+8f51c39
- cuda              : cuda_10.2.89_440.33.01_linux
- cudnn            : cudnn-10.2-linux-x64-v8.0.1.13
- tensorRT       : TensorRT-7.1.3.4
- mmdetection : master
- gcc                : 7.1

on the other hand , i will try the different way:

1. Annotating the code about matplotlib in mmdetection, It seems complicated ！
2. rebuilding your project from a cleaning docker env;

**Comment by grimoire** [comment]
OK
I will debug on a docker with the enviroment you provided. Please give me some time.

**Comment by cefengxu** [comment]
Sorry. I think the error may be caused by the backend of matplotlib.  When the backend be changed to 'Agg', the code is run normally.

However, another error output. I will update a new issue to describe it. 

Thanks man~
