### ISSUE TITLE
How to change the class scores before it is sent to nms?

### ISSUE THREAD

**Issue by 1224wxwx** [grimoire/mmdetection-to-tensorrt#46]
First , I want to thanks for your great job, it really helped me a lot. Could you please help me to solve the question below?

I changed the method "get_bboxes" of class "BBoxHead" and added a new parameter for original "mmdetection" in the test mode.  This parameter is a function which I did some tricks so as to change the scores(the result of F.sofmax...). 

If I want to make the same change in "mmdetection-to-tensorrt", what should I do? Or how can I get the original scores out of the get_bboxes method when I use "mmdetection-to-tensorrt"?

**Comment by grimoire** [comment]
Hi
Most module in mmdetection has it's coresponding wrapper in this project, such as [BBoxHead](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/bbox_heads/bbox_head.py) and [BBoxHeadWrapper](https://github.com/grimoire/mmdetection-to-tensorrt/blob/master/mmdet2trt/models/roi_heads/bbox_heads/bbox_head.py).
The wrapper turn the module to a **convertable** one. Try add your code in the wrapper, see if it works.
