### ISSUE TITLE
Warning: Encountered known unsupported method torch.Tensor.new_tensor

### ISSUE THREAD

**Issue by whoNamedCody** [grimoire/mmdetection-to-tensorrt#49]
Cascade RCNN convert, any advice ? Thanks

**Comment by grimoire** [comment]
Just ignore it.

**Comment by whoNamedCody** [comment]
thank you for your reply，but how to choose device dynamic
```
device='cuda:1'
trt_model = init_detector(trt_model_path).to(device)
```
not work

**Comment by grimoire** [comment]
The model can only work on the device you convert it.
If you want to use another device, please set the enviroment variable `CUDA_VISIBLE_DEVICES`
