### ISSUE TITLE
inference compare between trt and pytorch

### ISSUE THREAD

**Issue by cefengxu** [grimoire/mmdetection-to-tensorrt#5]
HI~

i using inference with 20 pics for testing **Speed** , **GPU Memory-Usage** of tensorrt and  pytorch, respectivly.

env:
config : faster_rcnn_r50_fpn_1x_coco.py
checkpoint : faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
GPU: TITAN X (Pascal)

the result is all most the same , but :

- Question 1 : tensorrt will spent longest time for the fist pic? 
- Question 2 : tensorrt doesn't seem to have any improvement in Speed and GPU Memory-Usage?

```
[trt] inference take time 1.2806954383850098 s , detect 8 objects
[trt] inference take time 0.07403969764709473 s , detect 22 objects
[trt] inference take time 0.0725240707397461 s , detect 11 objects
[trt] inference take time 0.0938711166381836 s , detect 3 objects
[trt] inference take time 0.18393778800964355 s , detect 4 objects
[trt] inference take time 0.07542586326599121 s , detect 3 objects
[trt] inference take time 0.07514834403991699 s , detect 5 objects
[trt] inference take time 0.0743105411529541 s , detect 19 objects
[trt] inference take time 0.06311678886413574 s , detect 33 objects
[trt] inference take time 0.07394289970397949 s , detect 3 objects
[trt] inference take time 0.08452844619750977 s , detect 5 objects
[trt] inference take time 0.07141757011413574 s , detect 28 objects
[trt] inference take time 0.07546305656433105 s , detect 54 objects
[trt] inference take time 0.06720089912414551 s , detect 9 objects
[trt] inference take time 0.07281136512756348 s , detect 4 objects
[trt] inference take time 0.06780433654785156 s , detect 56 objects
[trt] inference take time 0.0691215991973877 s , detect 17 objects
[trt] inference take time 0.07524847984313965 s , detect 13 objects
[trt] inference take time 0.08305907249450684 s , detect 31 objects
[trt] inference take time 0.0662374496459961 s , detect 39 objects
[trt] inference average time 0.13999524116516113 s

[torch] inference take time 0.08921217918395996 s 
[torch] inference take time 0.08358907699584961 s 
[torch] inference take time 0.08429265022277832 s 
[torch] inference take time 0.08585500717163086 s 
[torch] inference take time 0.07990050315856934 s 
[torch] inference take time 0.08589792251586914 s 
[torch] inference take time 0.09028077125549316 s 
[torch] inference take time 0.09110355377197266 s 
[torch] inference take time 0.08078670501708984 s 
[torch] inference take time 0.08568334579467773 s 
[torch] inference take time 0.09473133087158203 s 
[torch] inference take time 0.08323526382446289 s 
[torch] inference take time 0.08632254600524902 s 
[torch] inference take time 0.08114051818847656 s 
[torch] inference take time 0.08165812492370605 s 
[torch] inference take time 0.08303499221801758 s 
[torch] inference take time 0.08093047142028809 s 
[torch] inference take time 0.08914780616760254 s 
[torch] inference take time 0.08186078071594238 s 
[torch] inference take time 0.07793211936950684 s 
[torch] inference average time 0.08482978343963624 s
```

`Memory-Usage : 2110MiB / 12188MiB`

**Comment by grimoire** [comment]
Hi

I will try to explain these question one by one.
1. tensorrt will try to alloc the memory and do some preprocess about the engine and context. It is alway a good idea to warmup the network(actually, network of pytorch need warmup too.), you can feed some dummy input to the model before you use it.
2. About the inference time and memory usage, there might be multiple reason:
   first, guess you are using fp32 mode, right? **fp16 mode** will have much faster speed with the cost of few precision(very little, almost can be ignored), fp16 mode are always a better choice. 
  second, do you synchronize cuda stream when you count the inference time? Cuda kernel will be streaming in gpu when the network is running. Pytorch or tensorrt return something doesn't means they finish all operations(only means all operation has been queued to gpu). add tick-tock after that might not give you real inference time. Try add `torch.cuda.synchronize()` after inference code. (you might found that pytorch also take long time in first frame.)

In my device, faster-rcnn with input shape (1,3,800,1312):
 fp32:
 trt take time:  0.04453961849212647
 pytorch take time:  0.061907482147216794

 fp16:
 trt take time:  0.018731284141540527
 pytorch take time:  0.055935001373291014

**Comment by cefengxu** [comment]
when i generate the trt model via using mmdet2trt(  fp16_mode=True )
the log will output:
[TensorRT] WARNING: Half2 support requested on hardware without native FP16 support, performance will be negatively affected.

is it mean the CPU no support FP16??

**Comment by grimoire** [comment]
Here are the anwser from nvidia:
[https://forums.developer.nvidia.com/t/fp16-support-on-gtx-1060-and-1080/53256](https://forums.developer.nvidia.com/t/fp16-support-on-gtx-1060-and-1080/53256)

> FP16 is supported but at a low rate. So performance won't be interesting. The driver version you have should be fine. I would recommend using CUDA 8.0.61 (CUDA 8 GA2) which is what is currently publicly available.
> 
> The only GPUs with full-rate FP16 performance are Tesla P100, Quadro GP100, and Jetson TX1/TX2.
> 
> All GPUs with compute capability 6.1 (e.g. GTX 1050, 1060, 1070, 1080, Pascal Titan X, Titan Xp, Tesla P40, etc.) have low-rate FP16 performance. It's not the fast path on these GPUs. All of these GPUs should support "full rate" INT8 performance, however.

I am still trying add int8 support, but guess it will take long time.

Try warmup your model before inference. fp32 will get some bonus too.

**Comment by cefengxu** [comment]
Yes ~!
 i have updated the code  via` torch.cuda.synchronize('cuda:0')` to statistics the inference between mmdet2trt and mmdetection , and then mmdet2trt  speed up by 13%


  | torch |   | trt |  
-- | -- | -- | -- | --
image | inference | objs be detected| inference | objs be detected
000003.jpg | 0.0888180733 | 8 | 1.2400956154 | 8
000009.jpg | 0.0878646374 | 22 | 0.0666246414 | 22
000020.jpg | 0.0820932388 | 11 | 0.0703969002 | 11
000013.jpg | 0.0830266476 | 3 | 0.0695712566 | 3
000019.jpg | 0.0801789761 | 4 | 0.0673627853 | 4
000012.jpg | 0.0882394314 | 3 | 0.0829980373 | 3
000007.jpg | 0.0871551037 | 4 | 0.0752086639 | 5
000016.jpg | 0.0895793438 | 19 | 0.0839416981 | 19
000004.jpg | 0.0743381977 | 33 | 0.068041563 | 33
000002.jpg | 0.0871784687 | 3 | 0.0754187107 | 3
000011.jpg | 0.0898630619 | 5 | 0.0771043301 | 5
000010.jpg | 0.0831506252 | 28 | 0.0735895634 | 28
000014.jpg | 0.0876681805 | 54 | 0.0740339756 | 54
000015.jpg | 0.0803148746 | 9 | 0.067293644 | 9
000018.jpg | 0.0776650906 | 4 | 0.0663657188 | 4
000008.jpg | 0.0781502724 | 57 | 0.068205595 | 56
000017.jpg | 0.0778365135 | 18 | 0.0688450336 | 17
000001.jpg | 0.0857608318 | 13 | 0.0747027397 | 13
000006.jpg | 0.0789132118 | 31 | 0.0701141357 | 31
000005.jpg | 0.0772767067 | 39 | 0.0677347183 | 39
