### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'serialize'

### ISSUE THREAD

**Issue by caiduoduo12138** [grimoire/mmdetection-to-tensorrt#58]
When I build on cascade rcnn ,error occours. Can you give me some advice, thanks.

Use load_from_local loader
Warning: Encountered known unsupported method torch.Tensor.new_tensor
Warning: Encountered known unsupported method torch.Tensor.new_tensor
Warning: Encountered known unsupported method torch.Tensor.new_tensor
Warning: Encountered known unsupported method torch.Tensor.new_tensor
Warning: Encountered known unsupported method torch.Tensor.new_tensor
Warning: Encountered known unsupported method torch.Tensor.new_tensor
[TensorRT] WARNING: TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.0
[TensorRT] INFO: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[TensorRT] INFO: Detected 1 inputs and 4 output network tensors.
[TensorRT] ERROR: Internal error: plugin node (Unnamed Layer* 62) [PluginV2DynamicExt]requires 1342177280 bytes of scratch space, but only 500000000 is available. Try increasing the workspace size with IBuilder::setMaxWorkspaceSize()
[TensorRT] ERROR: ../builder/cudnnBuilder2.cpp (1597) - OutOfMemory Error in buildSingleLayer: 0
Traceback (most recent call last):
  File "inference.py", line 79, in <module>
    main()
  File "inference.py", line 43, in main
    torch.save(trt_model.state_dict(), args.save_path)
  File "/home/cai/anaconda3/envs/trt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 902, in state_dict
    hook_result = hook(self, destination, prefix, local_metadata)
  File "/home/cai/mmd2trt/torch2trt_dynamic/torch2trt_dynamic/torch2trt_dynamic.py", line 449, in _on_state_dict
    state_dict[prefix + 'engine'] = bytearray(self.engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'

**Comment by huweishenme** [comment]
I meet the same problem, how to fix it?

**Comment by zkccpro** [comment]
ANYONE fixed it????
