### ISSUE TITLE
solov2 support

### ISSUE THREAD

**Issue by elepherai** [grimoire/mmdetection-to-tensorrt#67]
Since [solov2](https://github.com/WXinlong/SOLO) is based on mmdetecion, do you have any plan to solov2 support?

**Comment by grimoire** [comment]
This PR is mainly focused on mmdetection official repo. If you want to add support to other model, you can write your own head wrapper like [this](https://github.com/grimoire/mmdetection-to-tensorrt/tree/master/mmdet2trt/models/dense_heads).
