### ISSUE TITLE
Does model.engine depend on CUDA version?

### ISSUE THREAD

**Issue by Kaeseknacker** [grimoire/mmdetection-to-tensorrt#70]
Hi,
I have a question about converting and reusing the TensorRT model (.engine file for c++ inference):

Does the model.engine depend on the CUDA version? e.g. converting a model with CUDA 10.2 and inference with a c++ application which is linked against CUDA 11.1.

In my case this doesn't work. I had to reconvert my models.

In [this doku](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#faq) ("Q: If I build the engine on one GPU and run the engine on another GPU, does this work?") it is described that the CUDA compute capability version of the GPU and the TensorRT version must be the same.
In my case the GPU was the same and the TensorRT Version nearly? the same:
```
TensorRT-7.2.2.3.Ubuntu-16.04.x86_64-gnu.cuda-10.2.cudnn8.0
TensorRT_7.2.2.3.Ubuntu-16.04.x86-64_gnu.cuda-11.1.cudnn8.0
```
Still, I couldn't reuse the model.
Therefore I suspect that the conversion also depends on the CUDA version.

Has anyone had similar experiences?

**Comment by grimoire** [comment]
I guess the answer is YES. If you want to know the detail about this, you better ask this question on the Nvidia forum.
If you do need to use the engine on a device with a different CUDA version, you can try to deploy the engine in a docker container with the same CUDA version.

**Comment by Kaeseknacker** [comment]
Thanks for your reply.
docker is a good idea. I should try it out. Does your docker file contain a fixed cuda version? I haven't written a docker file myself yet.

**Comment by grimoire** [comment]
The docker is built based on [this](https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/rel_20-12.html#rel_20-12)  so theoretically cuda==11.1.
