### ISSUE TITLE
Can not convert custom mmdet to tensorrt

### ISSUE THREAD

**Issue by selimceylan** [grimoire/mmdetection-to-tensorrt#92]
**Describe the bug**
I am trying to convert Oriented R CNN (which is one of the detection method from OBB) to tensorrt. There are some modules which mmdet has not, therefore I need to write mine. For example MidpointOffsetCoder.py is a special code for Oriented RCNN and neither mmdet nor mmdet2trt has not this code. Can you give some advices for handle this please ? 

Oriented RCNN: https://github.com/jbwang1997/OBBDetection/tree/master/configs/obb/oriented_rcnn
OBB Detection: https://github.com/jbwang1997/OBBDetection

**To Reproduce**
WARNING:root:can't find wrap module for type:<class 'mmdet.core.bbox.coder.obb.midpoint_offset_coder.MidpointOffsetCoder'>, use None instead.

WARNING:root:can't find wrap module for type:<class 'mmdet.models.roi_heads.roi_extractors.obb.obb_single_level_roi_extractor.OBBSingleRoIExtractor'>, use None instead.

WARNING:root:can't find wrap module for type:<class 'mmdet.models.roi_heads.bbox_heads.obb.obb_convfc_bbox_head.OBBShared2FCBBoxHead'>, use None instead.

**environment:**
Please provide your environment by:

```python
python tools/collect_env.py
```
Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.17
Python version: 3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-90-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: 
GPU 0: NVIDIA TITAN RTX
GPU 1: NVIDIA TITAN RTX

Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.0
Versions of relevant libraries:
[pip3] mmcv-full==1.3.9
[pip3] mmdet==2.11.0
[pip3] mmdet2trt==0.5.0
[pip3] tensorrt==8.0.0.3
[pip3] torch==1.10.0
[pip3] torch2trt-dynamic==0.5.0
[pip3] torchvision==0.11.1
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mmcv-full                 1.3.9                    pypi_0    pypi
[conda] mmdet                     2.11.0                   pypi_0    pypi
[conda] mmdet2trt                 0.5.0                     dev_0    <develop>
[conda] pytorch                   1.10.0          py3.7_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] tensorrt                  8.0.0.3                  pypi_0    pypi
[conda] torch2trt-dynamic         0.5.0                     dev_0    <develop>
[conda] torchvision               0.11.1               py37_cu113    pytorch

**Comment by grimoire** [comment]
Errr, I just rewrite the unsupported head. for example:

```python
# in  https://github.com/grimoire/mmdetection-to-tensorrt/blob/master/mmdet2trt/models/dense_heads/anchor_head.py
@register_wraper('mmdet.models.dense_heads.FSAFHead')
@register_wraper('mmdet.models.RetinaSepBNHead')
@register_wraper('mmdet.models.FreeAnchorRetinaHead')
@register_wraper('mmdet.models.RetinaHead')
@register_wraper('mmdet.models.SSDHead')
@register_wraper('mmdet.models.AnchorHead')
class AnchorHeadWraper(nn.Module):

    def __init__(self, module):
        super(AnchorHeadWraper, self).__init__()
        self.module = module
.....
```

then build the head with:

```python
# in https://github.com/grimoire/mmdetection-to-tensorrt/blob/master/mmdet2trt/models/detectors/single_stage.py
...
        mmdet_bbox_head = self.model.bbox_head
        self.bbox_head_wraper = build_wraper(mmdet_bbox_head)
...
```

`build_warper` will create the rewrite module.

You can write your own rewrite module by yourself.

**Comment by selimceylan** [comment]
Thanks for reply. I solved with this method but still need to rewrite some files.
