### ISSUE TITLE
Does it handles fuse conv and bn when convert to trt?

### ISSUE THREAD

**Issue by jinfagang** [grimoire/mmdetection-to-tensorrt#93]
Does it handles fuse conv and bn when convert to trt?

**Comment by grimoire** [comment]
This  repo convert PyTorch model to TensorRT network. Optimizations include layer fusion will be done on TensorRT. Read [this](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#enable-fusion) for more detail.
